version: "3"
services:
  consul1:
    image: "consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    volumes:
      - "/srv/consul:/consul/data"
    command: "consul agent -server -bootstrap-expect 3 --data-dir=/consul/data -ui -client=0.0.0.0"
  consul2:
    image: "consul:latest"
    container_name: "consul2"
    hostname: "consul2"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "consul agent -server -join consul1 --data-dir=/consul/data"
    depends_on:
      - consul1
  consul3:
    image: "consul:latest"
    container_name: "consul3"
    hostname: "consul3"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "consul agent -server -join consul1 --data-dir=/consul/data"
    depends_on:
      - consul1

